import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';
import {PDFDocument,PDFName,PDFRawStream,PDFDict} from 'pdf-lib';
import {generatePdf as createPdf} from '../src/pdf.js';
const fonts=await Promise.all(['DejaVuSans.ttf','DejaVuSans-Bold.ttf'].map(n=>fs.readFile(new URL('../public/fonts/'+n,import.meta.url))));
const generatePdf=(model,load,progress)=>createPdf(model,load,progress,fonts);import {buildReportModel} from '../src/domain.js';
// PNG and JPEG fixtures generated exclusively for QA.
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=','base64');
const data={obra:{id:'w',nome:'Obra de validação',empresa:'QA'},apartamentos:[{id:'a',pavimento:'13º',apartamento:'1301',status:'conforme'},{id:'b',pavimento:'13º',apartamento:'1302',status:'com_pendencias'}],servicos:[{nome:'Pintura'}],itens:[{id:'1',apartamento_id:'a',ambiente:'Sala',servico:'Pintura',status:'corrigido',criado_por_nome:'Ana da obra',atualizado_por_nome:'Bruno da obra',observacao:'Correção finalizada. Acentos: ação, vistoria, português.',foto_antes_path:'a/before.png',foto_depois_path:'a/after.png'},{id:'2',apartamento_id:'b',ambiente:'Quarto',servico:'Pintura',status:'pendente',observacao:'Reparar pintura.',foto_antes_path:'b/before.png'}]};
const antes=await fs.readFile(new URL('./fixtures/antes.jpg',import.meta.url));
const depois=await fs.readFile(new URL('./fixtures/depois.jpg',import.meta.url));
for(const tipo of ['pavimento','servico','pendencias','finalizacao'])test(`${tipo}: real PDF with embedded images`,async()=>{const m=buildReportModel(data,{tipo,pavimento:'13º',servico:tipo==='servico'?'Pintura':''});const blob=await generatePdf(m,async(item,kind)=>new Blob([kind==='depois'?depois:antes],{type:'image/jpeg'}));const bytes=new Uint8Array(await blob.arrayBuffer());assert.equal(Buffer.from(bytes.slice(0,5)).toString(),'%PDF-');const pdf=await PDFDocument.load(bytes);const imageCount=pdf.context.enumerateIndirectObjects().filter(([,object])=>object instanceof PDFRawStream&&object.dict.get(PDFName.of('Subtype'))===PDFName.of('Image')).length;assert.ok(imageCount>=m.items.length);const fontDescriptors=pdf.context.enumerateIndirectObjects().filter(([,object])=>object instanceof PDFDict&&object.get(PDFName.of('Type'))===PDFName.of('FontDescriptor'));assert.equal(fontDescriptors.length,2);assert.ok(fontDescriptors.every(([,font])=>font.has(PDFName.of('FontFile2'))),'Both fonts must be embedded in the PDF');assert.ok(pdf.getPageCount()>=2);await fs.mkdir('test-results',{recursive:true});await fs.writeFile(`test-results/${tipo}.pdf`,bytes);});
test('Required image failure aborts PDF generation instead of leaving an empty placeholder',async()=>{const m=buildReportModel(data,{tipo:'pavimento',pavimento:'13º'});await assert.rejects(generatePdf(m,async()=>{throw new Error('expired URL');}),/não foi gerado/);});
test('Long descriptions paginate without truncating the record',async()=>{const d=structuredClone(data);d.itens[0].observacao='Texto de vistoria com observação detalhada. '.repeat(250);const blob=await generatePdf(buildReportModel(d,{tipo:'pavimento',pavimento:'13º'}),async()=>new Blob([png]));const pdf=await PDFDocument.load(await blob.arrayBuffer());assert.ok(pdf.getPageCount()>3);});
