import test from 'node:test';import assert from 'node:assert/strict';
import {Repository} from '../src/repository.js';
const sample=()=>({id:'record-id',obra_id:'work-id',apartamento_id:'apartment-id',ambiente:'Sala QA',servico:'Pintura QA',status:'pendente',responsavel:'',observacao:'Teste',prioridade:'normal',photos:{antes:{blob:new Blob(['before'],{type:'image/jpeg'})}}});
function fake({uploadFail=false,dbFail=false,corruptDownload=false}={}){const calls=[],stored=new Map(),rows=new Map();const repo=new Repository({storage:{from:bucket=>({upload:async(path,blob)=>{calls.push('upload');if(uploadFail)return{error:new Error('Rede indisponível')};stored.set(path,blob);return{data:{path}};},download:async path=>({data:corruptDownload?new Blob(['x']):stored.get(path)}),remove:async()=>({data:[]})})},from:table=>({upsert:row=>{calls.push('write');return{select:()=>({single:async()=>{if(dbFail)return{error:new Error('Banco indisponível')};rows.set(row.id,row);return{data:row};}})};}})});repo.user={id:'user-id'};return{repo,calls,stored,rows};}
test('Failed upload does not create a database record and the draft retains the photo',async()=>{const {repo,calls,rows}=fake({uploadFail:true}),draft=sample();await assert.rejects(repo.saveDraft(draft),/Rede/);assert.equal(rows.size,0);assert.deepEqual(calls,['upload']);assert.equal(await draft.photos.antes.blob.text(),'before');});
test('Incomplete download verification prevents database write',async()=>{const {repo,calls}=fake({corruptDownload:true});await assert.rejects(repo.saveDraft(sample()),/confirmar/);assert.ok(!calls.includes('write'));});
test('Before and after must both upload before metadata is saved',async()=>{const {repo,calls}=fake(),draft=sample();draft.photos.depois={blob:new Blob(['after'],{type:'image/jpeg'})};const row=await repo.saveDraft(draft);assert.deepEqual(calls,['upload','upload','write']);assert.match(row.foto_antes_path,/user-id\/work-id\/apartment-id\/record-id\/antes-/);assert.match(row.foto_depois_path,/depois-/);assert.equal(row.foto_antes_data,undefined);});
test('Retry is idempotent and never overwrites the previously saved image',async()=>{const {repo,rows,stored}=fake(),draft=sample();draft.foto_antes_path='old-before.jpg';await repo.saveDraft(draft);const newPath=draft.photos.antes.path;await repo.saveDraft(draft);assert.equal(rows.size,1);assert.equal(stored.size,1);assert.notEqual(newPath,'old-before.jpg');assert.equal(rows.get(draft.id).foto_antes_path,newPath);});
test('Database failure preserves the draft for retry',async()=>{const {repo}=fake({dbFail:true}),draft=sample();await assert.rejects(repo.saveDraft(draft),/Banco/);assert.ok(draft.photos.antes.blob);assert.ok(draft.photos.antes.path);});
test('Saved report metadata is not inserted after failed PDF upload',async()=>{const {repo,calls}=fake({uploadFail:true});await assert.rejects(repo.saveReport({id:'pdf',blob:new Blob(['pdf'],{type:'application/pdf'}),model:{obra:{id:'w'}}}),/Rede/);assert.ok(!calls.includes('write'));});
