import { APT_STATUS, ITEM_STATUS, REPORT_TYPES, isOpen, isApproved, natural, sortApts, apartmentStatus, buildReportModel, dateTime, progressOf, isOverdue, catalogOptions, recordOptions, canManageWork, canDeleteRecord, authorName } from './domain.js';
import { PHOTOS, REPORTS } from './repository.js';
import { compressPhoto, drafts } from './photos.js';
import { generatePdf, pdfFilename, sharePdf, downloadPdf } from './pdf.js';
import { icon } from './icons.js';

const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const button=(text,action,ico='',extra='',cls='')=>`<button type="button" class="button ${cls}" data-action="${action}" ${extra}>${ico?icon(ico):''}${text}</button>`;
const options=(rows,selected='',empty='Selecione')=>`<option value="">${empty}</option>`+rows.map(([value,label])=>`<option value="${esc(value)}" ${value===selected?'selected':''}>${esc(label)}</option>`).join('');
const field=(label,name,value='',attrs='')=>`<label class="field"><span>${label}</span><input name="${name}" value="${esc(value)}" ${attrs}></label>`;
const select=(label,name,rows,value='',empty='Selecione',attrs='')=>`<label class="field"><span>${label}</span><select name="${name}" ${attrs}>${options(rows,value,empty)}</select></label>`;
const badge=(status,apartment=false)=>`<span class="badge status-${esc(status)}">${esc((apartment?APT_STATUS:ITEM_STATUS)[status]||status)}</span>`;
const empty=(title,detail,ico='building')=>`<div class="empty">${icon(ico)}<h3>${title}</h3><p>${detail}</p></div>`;
const errorText=e=> {
  if(e?.code==='23505')return 'Este cadastro já existe. Confira o nome ou o número do apartamento.';
  if(e?.code==='42501')return 'Você não tem acesso a este item. Confira sua sessão e tente novamente.';
  if(e?.code==='23514')return e.message;
  if(e?.message==='Invalid login credentials')return 'E-mail ou senha incorretos.';
  if(/fetch|network|offline/i.test(e?.message||''))return 'Não foi possível conectar. Confira a rede e tente novamente. Seus dados do formulário foram mantidos.';
  return e?.message||'Não foi possível concluir. Tente novamente.';
};

export async function mountApp(repo,root) {
  let user,data,obras=[],page='apartamentos',aptId='',floor='',query='',quick='',pendingService='',currentPdf=null,pdfUrl='',draft=null,draftKey='',draftTimer,processing=0,modalBusy=false,reportFilters={tipo:'pavimento',pavimento:'',servico:'',status:'',responsavel:''};
  const previewUrls=new Set();
  // Keep native file inputs in an ordinary modal to reduce iOS picker
  // integration risks. A physical iPhone must confirm the camera behavior.
  const backdrop=document.createElement('div');backdrop.className='modal-backdrop';backdrop.hidden=true;document.body.append(backdrop);
  const dialog=document.createElement('div');dialog.className='modal';dialog.setAttribute('role','dialog');dialog.setAttribute('aria-modal','true');dialog.setAttribute('aria-labelledby','modal-title');dialog.hidden=true;dialog.open=false;document.body.append(dialog);
  let lastFocused=null;
  const notices=document.createElement('div');notices.className='notices';notices.setAttribute('aria-live','polite');document.body.append(notices);
  const notify=(message,error=false)=>{const el=document.createElement('div');el.className='notice'+(error?' error':'');el.textContent=message;notices.replaceChildren(el);setTimeout(()=>el.remove(),error?14000:6000);};
  const setError=(scope,message)=>{const el=scope.querySelector('[data-error]');if(el){el.textContent=message;el.hidden=!message;el.scrollIntoView({block:'nearest',behavior:'smooth'});}else notify(message,true);};
  async function run(scope,task){const submit=scope?.querySelector('button[type="submit"]');if(submit?.disabled)return; if(submit)submit.disabled=true;if(scope)setError(scope,'');try{await task();}catch(e){setError(scope||root,errorText(e));}finally{if(submit)submit.disabled=false;}}
  const flashError='<div class="form-error" role="alert" data-error hidden></div>';
  const errorBox=()=>root.querySelector('[data-error]');
  const floors=()=>[...new Set(data.apartamentos.map(a=>a.pavimento))].sort(natural).map(v=>[v,v]);
  const rowById=(table,id)=>data[table].find(r=>r.id===id);
  const itemsFor=id=>data.itens.filter(i=>i.apartamento_id===id);
  const reportServices=()=>catalogOptions(data.servicos,'',true);
  const owner=()=>canManageWork(user,data?.obra);
  const mayDelete=row=>canDeleteRecord(user,data?.obra,row);
  const authors=row=>`<small class="authorship">Registrado por ${esc(authorName(row))}${row.atualizado_por_nome?`<br>Última alteração: ${esc(row.atualizado_por_nome)}`:''}</small>`;
  function freePreviews(){for(const url of previewUrls)URL.revokeObjectURL(url);previewUrls.clear();}
  function clearPdf(){if(pdfUrl)URL.revokeObjectURL(pdfUrl);pdfUrl='';currentPdf=null;}
  function showModal(title,body){
    const wasOpen=dialog.open;
    dialog.innerHTML=`<div class="modal-head"><h2 id="modal-title">${esc(title)}</h2>${button('','close','close','aria-label="Fechar"','icon-button')}</div><div class="modal-body">${body}</div>`;
    if(!wasOpen){lastFocused=document.activeElement;backdrop.hidden=false;dialog.hidden=false;dialog.open=true;}
    document.body.classList.add('modal-open');root.inert=true;
    dialog.querySelector('input,select,textarea,button')?.focus();
  }
  async function closeModal(){if(modalBusy || processing){notify('Aguarde concluir esta etapa.');return;}if(draft){clearTimeout(draftTimer);await rememberDraft();draft=null;}dialog.hidden=true;backdrop.hidden=true;dialog.open=false;dialog.innerHTML='';document.body.classList.remove('modal-open');root.inert=false;freePreviews();lastFocused?.focus?.();lastFocused=null;}
  backdrop.addEventListener('click',()=>{if(dialog.open)void closeModal();});
  document.addEventListener('keydown',e=>{
    if(!dialog.open)return;
    if(e.key==='Escape'){e.preventDefault();void closeModal();return;}
    if(e.key!=='Tab')return;
    const items=[...dialog.querySelectorAll('button,[href],input,select,textarea,[tabindex]:not([tabindex="-1"])')].filter(el=>!el.disabled&&el.offsetParent!==null);
    if(!items.length)return;
    const first=items[0],last=items[items.length-1];
    if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}
    else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}
  });
  function loginScreen(){root.innerHTML=`<main class="welcome"><div class="welcome-mark">${icon('building')}</div><p class="eyebrow">VISTORIA DE APARTAMENTOS</p><h1>Pente Fino</h1><p class="lead">Do primeiro registro<br>à última correção.</p><form data-form="login" class="panel login-form">${flashError}${field('E-mail','email','','type="email" autocomplete="username" required')}${field('Senha','password','','type="password" autocomplete="current-password" required')}<button type="submit" class="button primary wide">Entrar ${icon('arrow')}</button>${button('Esqueci minha senha','forgot-password','','','text-button')}<p class="small">Acesso privado à sua obra.</p></form></main>`;}
  function forgotPasswordScreen(email=''){root.innerHTML=`<main class="welcome"><h1>Recuperar senha</h1><form data-form="recover" class="panel login-form">${flashError}${field('E-mail da sua conta','email',email,'type="email" autocomplete="email" required')}<button type="submit" class="button primary wide">Enviar link</button><p class="small" data-recovery-message></p></form>${button('Voltar para entrar','auth-login','','','text-button')}</main>`;}
  function passwordScreen(){root.innerHTML=`<main class="welcome"><p class="eyebrow">PENTE FINO · ACESSO INDIVIDUAL</p><h1>Definir minha senha</h1><p>${esc(user.email)}</p><form data-form="password" class="panel login-form">${flashError}${field('Nova senha','password','','type="password" autocomplete="new-password" minlength="10" required')}${field('Repita a nova senha','confirmation','','type="password" autocomplete="new-password" minlength="10" required')}<p class="small">Use pelo menos 10 caracteres. Sua senha não será mostrada ao proprietário da obra.</p><button type="submit" class="button primary wide">Salvar senha e continuar</button></form>${button('Voltar para entrar','auth-login','','','text-button')}</main>`;}
  async function loadObras(){await repo.acceptInvites();obras=await repo.list('obras');}
  function obraScreen(){root.innerHTML=`<main class="container"><p class="eyebrow">PENTE FINO</p><div class="section-head"><h1>Suas obras</h1>${button('Sair','logout','logout')}</div><p class="muted">Escolha a obra que você vai vistoriar.</p>${flashError}<div class="cards">${obras.length?obras.map(o=>`<button class="project-card" data-action="select-obra" data-id="${o.id}">${icon('building')}<span><strong>${esc(o.nome)}</strong><small>${esc(o.empresa||'Obra residencial')}</small></span>${icon('arrow')}</button>`).join(''):empty('Sua primeira obra','Cadastre a obra para começar.')}</div>${button('Nova obra','new-obra','plus','','primary')}</main>`;}
  async function chooseObra(id){const obra=obras.find(o=>o.id===id);if(!obra)throw new Error('Obra indisponível.');data=await repo.load(obra);try{localStorage.setItem(`pf-obra-${user.id}`,id);}catch{}aptId='';floor='';pendingService='';page='apartamentos';reportFilters={tipo:'pavimento',pavimento:'',servico:'',status:'',responsavel:''};clearPdf();render();}
  async function start(){root.innerHTML='<main class="welcome"><p role="status">Carregando sua sessão…</p></main>';try{const invited=await repo.passwordLink?.();if(invited){user=invited;data=null;passwordScreen();return;}user=await repo.session();if(!user){loginScreen();return;}await loadObras();let previous;try{previous=localStorage.getItem(`pf-obra-${user.id}`);}catch{}if(obras.some(o=>o.id===previous))await chooseObra(previous);else obraScreen();}catch(e){root.innerHTML=`<main class="welcome"><h1>Não foi possível carregar</h1><p role="alert">${esc(errorText(e))}</p>${button('Tentar novamente','retry','refresh','','primary')}${button('Voltar para entrar','auth-login','','','text-button')}</main>`;}}
  function header(){return `<header class="header"><div class="header-inner"><button class="brand" data-action="obras" aria-label="Selecionar obra"><span class="brand-mark">${icon('building')}</span><span><small>PENTE FINO</small><strong>${esc(data.obra.nome)}</strong></span></button>${button('','reload','refresh','aria-label="Sincronizar"','icon-button')}</div></header>`;}
  function nav(){return `<nav class="bottom-nav" aria-label="Navegação principal">${[['apartamentos','Apartamentos','building'],['pendencias','Pendências','alert'],['relatorios','Relatórios','report'],['ajustes','Ajustes','settings']].map(([p,label,ico])=>`<button type="button" data-action="page" data-page="${p}" ${page===p?'aria-current="page"':''}>${icon(ico)}<span>${label}</span></button>`).join('')}</nav>`;}
  function render(){if(!data)return;root.innerHTML=header()+`<main class="container">${!navigator.onLine?'<div class="banner" role="status">Sem conexão. Conecte-se para salvar; o rascunho da foto fica neste aparelho.</div>':''}${flashError}${page==='apartamentos'?(aptId?apartmentView():apartmentsView()):page==='pendencias'?pendingView():page==='relatorios'?reportsView():settingsView()}</main>`+nav();void resolvePhotos(root);}
  function progressBar(prog,label='Progresso das correções'){return prog.total?`<div class="progress-block"><div class="progress-head"><span>${label}</span><strong>${prog.percent}%</strong></div><div class="progress-bar"><div class="progress-fill" style="width:${prog.percent}%"></div></div><p class="small muted">${prog.done} de ${prog.total} registro(s) corrigido(s) ou conforme</p></div>`:'';}
  function apartmentsView(){const approved=data.apartamentos.filter(a=>isApproved({status:apartmentStatus(a,data.itens)})).length;return `<div class="section-head"><div><p class="eyebrow">SUA OBRA, UNIDADE POR UNIDADE</p><h1>Apartamentos</h1></div>${owner()?button('Adicionar','new-apt','plus','','primary'):''}</div><div class="metrics"><div><strong>${data.apartamentos.length}</strong><span>apartamentos</span></div><div><strong>${approved}</strong><span>conformes / finalizados</span></div><div><strong>${data.itens.filter(isOpen).length}</strong><span>pendências</span></div></div>${progressBar(progressOf(data.itens))}<div class="filters">${select('Pavimento','floor',floors(),floor,'Todos','data-filter="floor"')}${field('Buscar apartamento','query',query,'placeholder="Número do apartamento" data-filter="query"')}</div><div id="apartment-list">${apartmentList()}</div>`;}
  function apartmentList(){const rows=data.apartamentos.filter(a=>(!floor||a.pavimento===floor)&&(!query||a.apartamento.toLowerCase().includes(query.toLowerCase()))).sort(sortApts);return rows.length?rows.map(a=>{const items=itemsFor(a.id),open=items.filter(isOpen).length,prog=progressOf(items);return `<button type="button" class="apartment-card" data-action="open-apt" data-id="${a.id}"><div class="apt-number">${esc(a.apartamento)}</div><div class="apt-info"><small>${esc(a.pavimento)}</small>${badge(apartmentStatus(a,data.itens),true)}<p>${items.length} registro(s)${open?` · ${open} pendência(s)`:''}</p>${items.length?`<div class="mini-bar" aria-hidden="true"><span style="width:${prog.percent}%"></span></div>`:''}</div>${icon('arrow')}</button>`;}).join(''):empty(data.apartamentos.length?'Nenhum apartamento encontrado':'Comece pelos apartamentos',data.apartamentos.length?'Ajuste os filtros acima.':'Adicione o pavimento e os números das unidades.');}
  function apartmentView(){const a=rowById('apartamentos',aptId);if(!a){aptId='';return apartmentsView();}const rows=itemsFor(a.id).filter(i=>!quick||(quick==='abertos'?isOpen(i):!isOpen(i)));return `${button('Apartamentos','back','back','','text-button')}<div class="section-head"><div><p class="eyebrow">${esc(a.pavimento)}</p><h1>Apartamento ${esc(a.apartamento)}</h1></div>${owner()?button('','edit-apt','edit',`data-id="${a.id}" aria-label="Editar apartamento"`,'icon-button'):''}</div>${badge(apartmentStatus(a,data.itens),true)}${a.atualizado_por_nome?`<p class="small muted">Última atualização: ${esc(a.atualizado_por_nome)} · ${dateTime(a.updated_at)}</p>`:''}<div class="primary-actions">${button('Novo registro fotográfico','new-item','camera','','primary large')}${button('Classificar como Conforme','conforme','check','','large')}</div>${progressBar(progressOf(itemsFor(a.id)))}<div class="section-head"><h2>Registros <span class="count">${itemsFor(a.id).length}</span></h2>${button('Finalizar apartamento','finalizado','check','','text-button')}</div><div class="segmented" aria-label="Filtrar registros">${[['','Todos'],['abertos','Pendentes'],['fechados','Corrigidos']].map(([v,l])=>`<button type="button" data-action="quick-filter" data-value="${v}" aria-pressed="${quick===v}">${l}</button>`).join('')}</div><div class="record-grid">${rows.length?rows.sort((a,b)=>String(b.created_at).localeCompare(String(a.created_at))).map(i=>recordCard(i)).join(''):empty('Nenhum registro aqui','Registre um problema ou classifique o apartamento como Conforme.','camera')}</div>`;}
  function deadlineTag(i){if(!i.prazo)return '';const overdue=isOverdue(i);const formatted=new Date(i.prazo+'T00:00:00').toLocaleDateString('pt-BR');return `<span class="deadline${overdue?' overdue':''}">${overdue?'Atrasado · ':'Prazo '}${formatted}</span>`;}
  function recordCard(i,showApt=false){const a=rowById('apartamentos',i.apartamento_id);const kind=i.foto_depois_path?'depois':'antes';return `<button type="button" class="record-card" data-action="edit-item" data-id="${i.id}"><div class="record-image">${photoHtml(i,kind)}<span>${kind==='antes'?'Antes':'Depois'}</span></div><div class="record-info">${showApt?`<p class="eyebrow">${esc(a?.pavimento)} · Apto ${esc(a?.apartamento)}</p>`:''}<div class="record-head"><h3>${esc(i.servico)}</h3>${icon('edit')}</div><p>${esc(i.ambiente)}</p>${badge(i.status)}${deadlineTag(i)}${i.observacao?`<p class="note">${esc(i.observacao)}</p>`:''}${authors(i)}<small>${dateTime(i.updated_at||i.created_at)}</small></div></button>`;}
  function photoHtml(i,kind){const path=i[`foto_${kind}_path`],legacy=i[`foto_${kind}_data`];if(path)return `<img data-photo="${esc(path)}" alt="Foto ${kind}" loading="lazy">`;if(legacy && /^data:image\/(jpeg|png);base64,/.test(legacy))return `<img src="${esc(legacy)}" alt="Foto ${kind}" loading="lazy">`;return `<div class="photo-empty">${icon('camera')}<span>Sem foto ${kind}</span></div>`;}
  async function resolvePhotos(scope){const imgs=[...scope.querySelectorAll('img[data-photo]')];await Promise.all(imgs.map(async img=>{try{const path=img.dataset.photo;const url=await repo.signedPhoto(path);if(!img.isConnected)return;img.src=url;img.onerror=()=>{img.hidden=true;const p=document.createElement('span');p.className='photo-error';p.textContent='Foto indisponível. Sincronize para tentar novamente.';img.after(p);};}catch{if(img.isConnected){img.hidden=true;const p=document.createElement('span');p.className='photo-error';p.textContent='Não foi possível carregar a foto. Sincronize para tentar novamente.';img.after(p);}}}));}
  function pendingView(){return `<div class="section-head"><div><p class="eyebrow">ACOMPANHAMENTO DAS CORREÇÕES</p><h1>Pendências</h1></div></div><div class="filters">${select('Pavimento','floor',floors(),floor,'Todos','data-filter="pending-floor"')}${select('Serviço','service',reportServices(),pendingService,'Todos','data-filter="pending-service"')}</div><div id="pending-list" class="record-grid">${pendingList()}</div>`;}
  function pendingList(service=pendingService){const rows=data.itens.filter(i=>isOpen(i)&&(!floor||rowById('apartamentos',i.apartamento_id)?.pavimento===floor)&&(!service||i.servico===service));return rows.length?rows.map(i=>recordCard(i,true)).join(''):empty('Nenhuma pendência neste filtro','As correções abertas aparecerão aqui.','check');}
  function reportsView(){return `<div class="section-head"><div><p class="eyebrow">REGISTROS QUE VIRAM DOCUMENTOS</p><h1>Relatórios</h1></div></div><form class="panel" data-form="report">${flashError}<div class="two-columns">${select('Tipo de relatório','tipo',Object.entries(REPORT_TYPES),reportFilters.tipo,'','required')}${select('Pavimento','pavimento',floors(),reportFilters.pavimento||floor,'Todos / selecione')}</div><div class="report-extra two-columns" ${['servico','pendencias'].includes(reportFilters.tipo)?'':'hidden'}>${select('Serviço','servico',reportServices(),reportFilters.servico,'Todos / selecione')}${select('Status','status',Object.entries(ITEM_STATUS),reportFilters.status,'Padrão do relatório')}${field('Responsável','responsavel',reportFilters.responsavel,'placeholder="Filtrar por nome ou equipe"')}</div><button type="submit" class="button primary">${icon('report')}Gerar PDF</button><p role="status" data-progress class="small"></p></form>${currentPdf?pdfPanel():''}<div class="section-head"><h2>PDFs salvos <span class="count">${data.relatorios.length}</span></h2></div><div class="cards">${data.relatorios.length?data.relatorios.sort((a,b)=>String(b.created_at).localeCompare(String(a.created_at))).map(r=>`<div class="saved-report"><div class="report-file">${icon('report')}</div><div><h3>${esc(r.titulo)}</h3><p>${dateTime(r.created_at)}</p>${authors(r)}${!r.pdf_path?'<p class="small">Relatório antigo sem PDF. Gere um novo documento.</p>':''}<div class="inline-actions">${r.pdf_path?button('Abrir / compartilhar','open-report','eye',`data-id="${r.id}"`):''}${mayDelete(r)?button('Excluir','delete-report','trash',`data-id="${r.id}"`,'danger text-button'):''}</div></div></div>`).join(''):empty('Nenhum PDF salvo','Gere um relatório e toque em “Salvar no app”.','report')}</div>`;}
  function pdfPanel(){return `<section class="panel pdf-panel"><p class="eyebrow">PDF PRONTO${currentPdf.saved?' · SALVO NO APP':''}</p><h2>${esc(currentPdf.title)}</h2>${currentPdf.model?.tipo==='finalizacao'?`<p class="muted">${currentPdf.model.summary.correctionTotal ? `Progresso das correções: ${currentPdf.model.summary.correctionPercent}%` : 'Sem registros para medir correções.'}</p><p class="${currentPdf.model.summary.notApproved?'banner':'muted'}">${esc(currentPdf.model.summary.conclusion)}</p>`:''}<p class="small">${(currentPdf.blob.size/1024).toFixed(0)} KB · Imagens incorporadas</p><div class="pdf-actions">${button('Visualizar','view-pdf','eye')}${button('Salvar no app','save-pdf','save',currentPdf.saved?'disabled':'','primary')}${button('Compartilhar','share-pdf','share')}${button('Baixar','download-pdf','download')}</div></section>`;}
  function settingsView(){return `<div class="section-head"><div><p class="eyebrow">SUA OBRA E SUA EQUIPE</p><h1>Ajustes</h1></div></div><div class="panel"><div class="section-head"><div><h2>${esc(data.obra.nome)}</h2><p>${esc(data.obra.empresa||'')}</p><p class="small muted">${owner()?'Você é o proprietário desta obra.':'Você participa da equipe desta obra.'}</p></div>${owner()?button('Editar','edit-obra','edit'):''}</div>${button('Trocar obra','obras','building')}</div>${teamView()}${owner()?`<div class="two-columns">${catalog('ambientes','Ambientes','Ambiente')}${catalog('servicos','Serviços','Serviço')}${catalog('prioridades','Prioridades','Prioridade')}</div>`:'<p class="small muted">O proprietário gerencia apartamentos, ambientes, serviços e prioridades. A equipe registra e acompanha as vistorias.</p>'}${activityView()}<div class="panel account"><p class="small">${esc(user.email||'Sessão privada')}</p>${button('Sair da conta','logout','logout','','danger')}</div><p class="version">Pente Fino · versão 1.3.0</p>`;}
  function teamView(){
    const members=data.membros_obra.filter(m=>m.ativo), pending=data.convites_obra.filter(i=>i.ativo&&!i.aceito_por);
    return `<section class="panel"><h2>Equipe da obra</h2><p>Os participantes veem os mesmos checklists, fotos e PDFs e podem registrar e atualizar correções. A autoria é preservada.</p>${owner()?`<form data-form="member">${flashError}<div class="two-columns">${field('Nome do colega','nome','','required maxlength="150" autocomplete="off"')}${field('E-mail da conta','email','','type="email" required maxlength="254" autocomplete="off"')}</div><button type="submit" class="button primary">Convidar colega</button><p class="small muted">O colega receberá um link para definir a própria senha. Quem já tem conta usa a senha atual. O acesso vale apenas para esta obra.</p></form>`:''}<ul class="catalog-list"><li><span>Proprietário da obra${owner()?' (você)':''}</span></li>${members.map(m=>`<li><span>${esc(m.nome)}${m.user_id===user.id?' (você)':''}</span>${owner()?button('Remover acesso','revoke-member','close',`data-id="${m.id}"`,'text-button danger'):''}</li>`).join('')}${pending.map(i=>`<li><span>${esc(i.nome)}<small>${esc(i.email)} · ${esc(({pendente:'aguarda envio',enviando:'envio em andamento',enviado:'enviado · aguarda aceite',conta_existente:'conta existente · aguarda entrada',falhou:'falha no envio'})[i.status_envio]||'aguarda envio')}</small></span>${button('Reenviar','resend-invite','refresh',`data-id="${i.id}"`,'text-button')}${button('Cancelar','revoke-invite','close',`data-id="${i.id}"`,'text-button danger')}</li>`).join('')}</ul></section>`;
  }
  function activityView(){
    const entities={chk_itens:'Registro',chk_apartamentos:'Apartamento',chk_relatorios:'Relatório'}, actions={INSERT:'criou',UPDATE:'atualizou',DELETE:'excluiu'};
    return `<section class="panel"><h2>Atividade da equipe</h2><p class="small muted">As 50 alterações mais recentes, a partir da ativação do compartilhamento.</p><ul class="activity-list">${data.atividades.map(a=>{const d=a.detalhes||{},apt=rowById('apartamentos',d.apartamento_id);return `<li><strong>${esc(a.autor_nome)}</strong> ${actions[a.acao]||esc(a.acao)} ${entities[a.entidade]||'cadastro'}<p>${esc(d.titulo||d.servico||d.apartamento||'')}${apt?` · Apto ${esc(apt.apartamento)}`:''}${d.status?` · ${esc(ITEM_STATUS[d.status]||APT_STATUS[d.status]||d.status)}`:''}</p><small>${dateTime(a.created_at)}</small></li>`;}).join('')||'<li class="muted">Nenhuma alteração registrada desde a ativação.</li>'}</ul></section>`;
  }
  function catalog(table,title,singular){return `<section class="panel"><div class="section-head"><h2>${title} <span class="count">${data[table].length}</span></h2></div><form data-form="catalog" data-table="${table}">${flashError}${field(`Nome do ${singular.toLowerCase()}`,'nome','','required maxlength="100" autocomplete="off"')}<button type="submit" class="button">${icon('plus')}Adicionar ${singular.toLowerCase()}</button></form><ul class="catalog-list">${data[table].map(row=>`<li><span>${esc(row.nome)}${row.ativo===false?' (inativo)':''}</span>${button('',row.ativo===false?'reativar-catalog':'inativar-catalog',row.ativo===false?'check':'close',`data-table="${table}" data-id="${row.id}" aria-label="${row.ativo===false?'Reativar':'Inativar'} ${esc(row.nome)}"`,'icon-button')}${button('','edit-catalog','edit',`data-table="${table}" data-id="${row.id}" aria-label="Editar ${esc(row.nome)}"`,'icon-button')}${button('','delete-catalog','trash',`data-table="${table}" data-id="${row.id}" aria-label="Excluir ${esc(row.nome)}"`,'icon-button danger')}</li>`).join('')||`<li class="small muted">Nenhum ${singular.toLowerCase()} cadastrado.</li>`}</ul><p class="small muted">Inativar remove ${singular.toLowerCase()} das opções para novos registros, sem apagar o histórico.</p></section>`;}
  function obraForm(existing){showModal(existing?'Editar obra':'Nova obra',`<form data-form="obra" data-id="${existing?.id||''}">${flashError}${field('Nome da obra','nome',existing?.nome,'required maxlength="140"')}${field('Empresa / construtora','empresa',existing?.empresa,'maxlength="140"')}<button type="submit" class="button primary wide">Salvar obra</button></form>`);}
  function aptForm(existing){showModal(existing?'Editar apartamento':'Adicionar apartamentos',`<form data-form="apt" data-id="${existing?.id||''}">${flashError}${field('Pavimento','pavimento',existing?.pavimento||floor,'required maxlength="70" placeholder="Ex.: 13º pavimento"')}${field(existing?'Apartamento':'Apartamentos (separados por vírgula)','apartamento',existing?.apartamento,'required maxlength="1500" placeholder="Ex.: 1301, 1302"')}<button type="submit" class="button primary wide">Salvar apartamentos</button></form>`);}
  async function rememberDraft(){if(!draft)return;try{await drafts.put(draftKey,draft);}catch{notify('Não foi possível guardar o rascunho neste aparelho. Mantenha esta tela aberta até salvar.',true);}}
  async function openDraft(item,fresh=false){
    const targetApt=item?.apartamento_id||aptId; if(!targetApt)return;
    draftKey=`${user.id}/${data.obra.id}/${targetApt}/${item?.id||'novo'}`;
    let restored;try{restored=await drafts.get(draftKey);}catch{}
    if(item&&!fresh){try{const latest=await repo.get('itens',item.id);if(!latest&&!restored)throw new Error('Registro removido ou sem acesso. Sincronize a lista.');item=latest||item;}catch(e){if(!restored&&navigator.onLine)throw e;}}
    const choices=recordOptions(data,restored||item||{});
    if(!choices.ambientes.length||!choices.servicos.length){showModal('Prepare os cadastros',`<p>Cadastre ou reative ambientes e serviços para criar um novo registro.</p>${button('Ir para Ajustes','go-settings','settings','','primary wide')}`);return;}
    draft=restored||{id:item?.id||crypto.randomUUID(),user_id:item?.user_id||user.id,versao:item?.versao,obra_id:data.obra.id,apartamento_id:targetApt,ambiente:item?.ambiente||'',servico:item?.servico||'',status:ITEM_STATUS[item?.status]?item.status:'pendente',observacao:item?.observacao||'',responsavel:item?.responsavel||'',prioridade:item?.prioridade??(data.prioridades.length?'':'normal'),prazo:item?.prazo||'',foto_antes_path:item?.foto_antes_path||null,foto_depois_path:item?.foto_depois_path||null,data_correcao:item?.data_correcao||null,photos:{},existing:!!item};
    const a=rowById('apartamentos',targetApt);
    const {ambientes:envRows,servicos:servRows,prioridades:prioRows}=recordOptions(data,draft);
    showModal(item?'Editar registro':'Novo registro fotográfico',`<p class="eyebrow">${esc(a.pavimento)} · APTO ${esc(a.apartamento)}</p>${item?authors(item):''}${restored?'<div class="banner">Rascunho recuperado neste aparelho.</div>':''}<form data-form="item">${flashError}<div class="two-columns">${select('Ambiente','ambiente',envRows,draft.ambiente,'Selecione','required')}${select('Serviço','servico',servRows,draft.servico,'Selecione','required')}</div><label class="field"><span>Observação / descrição</span><textarea name="observacao" rows="3" maxlength="8000" placeholder="Descreva o que precisa ser corrigido">${esc(draft.observacao)}</textarea></label><div class="two-columns">${select('Status','status',Object.entries(ITEM_STATUS),draft.status,'Selecione','required')}${field('Responsável (opcional)','responsavel',draft.responsavel,'maxlength="150" placeholder="Equipe ou profissional"')}</div><div class="two-columns">${select('Prioridade','prioridade',prioRows,draft.prioridade)}${field('Prazo para conclusão (opcional)','prazo',draft.prazo,'type="date"')}</div><div class="photo-fields">${photoField('antes')}${photoField('depois')}</div><p class="small" role="status" data-progress>Confira as fotos e salve o registro.</p><div class="form-error" role="alert" data-photo-error hidden></div><div class="form-footer"><button type="submit" class="button primary wide">${icon('save')}Salvar registro</button>${item?button('Recarregar registro','reload-item','refresh',`data-id="${item.id}"`,'text-button'):''}${item&&mayDelete(item)?button('Excluir registro','delete-item','trash',`data-id="${item.id}"`,'text-button danger'):''}</div></form>`);
    for(const kind of ['antes','depois'])if(draft.photos[kind]?.blob)showPhotoPreview(kind,draft.photos[kind].blob);
    void resolvePhotos(dialog);
  }
  function photoField(kind){return `<section class="photo-field"><h3>Foto ${kind} <small>${kind==='antes'?'Situação encontrada':'Correção / finalização'}</small></h3><div class="photo-preview" data-preview="${kind}">${photoHtml(draft,kind)}</div><div class="photo-actions"><label class="photo-picker primary">${icon('camera')}Tirar foto<input type="file" name="${kind}-camera" data-photo-input="${kind}" aria-label="Tirar foto ${kind}" accept="image/*" capture="environment"></label><label class="photo-picker">${icon('image')}Galeria<input type="file" name="${kind}-gallery" data-photo-input="${kind}" aria-label="Galeria foto ${kind}" accept="image/*"></label></div></section>`;}
  function showPhotoPreview(kind,blob){const box=dialog.querySelector(`[data-preview="${kind}"]`);if(!box)return;const url=URL.createObjectURL(blob);previewUrls.add(url);box.innerHTML=`<img src="${url}" alt="Prévia da foto ${kind}"><span class="photo-tag">Prévia · ${(blob.size/1024).toFixed(0)} KB</span>`;}
  const busyDraft=busy=>{dialog.querySelectorAll('input,select,textarea,button').forEach(el=>el.disabled=busy);modalBusy=busy;};
  async function setApartmentStatus(status){const a=rowById('apartamentos',aptId);if(itemsFor(a.id).some(isOpen))throw new Error('Corrija as pendências deste apartamento antes de classificá-lo como Conforme ou Finalizado.');const updated=await repo.update('apartamentos',a.id,{status});data.apartamentos=data.apartamentos.map(x=>x.id===a.id?updated:x);render();notify(status==='conforme'?'Apartamento classificado como Conforme.':'Apartamento finalizado.');}
  function pdfReady(blob,title,model=null,id=crypto.randomUUID(),saved=false){clearPdf();currentPdf={blob,title,model,id,saved};pdfUrl=URL.createObjectURL(blob);}
  let syncing=false;
  const editing=()=>dialog.open||root.querySelector('form[data-dirty="true"]')||root.querySelector('button[type="submit"]:disabled')||['INPUT','SELECT','TEXTAREA'].includes(document.activeElement?.tagName);
  async function refresh(background=false){
    if(!data||!user||(background&&(syncing||editing())))return;
    const workId=data.obra.id,userId=user.id;syncing=true;
    try {const next=await repo.load(data.obra);if(data?.obra.id!==workId||user?.id!==userId||(background&&editing()))return;
      const changed=JSON.stringify(data)!==JSON.stringify(next);data=next;if(changed||!background)render();
    } catch(e){if(e.code==='WORK_ACCESS'&&data?.obra.id===workId){data=null;clearPdf();await loadObras();obraScreen();notify(errorText(e),true);}else throw e;}
    finally{syncing=false;}
  }
  const backgroundSync=()=>{if(navigator.onLine&&document.visibilityState==='visible')void refresh(true).catch(()=>{});};
  async function act(el){
    const action=el.dataset.action,id=el.dataset.id;
    // Share and view execute synchronously in this tap before any I/O.
    if(action==='share-pdf'){if(currentPdf)sharePdf(currentPdf.blob,pdfFilename(currentPdf.title)).catch(e=>{if(e.name!=='AbortError')notify(errorText(e),true);});return;}
    if(action==='view-pdf'){if(pdfUrl){const a=document.createElement('a');a.href=pdfUrl;a.target='_blank';a.rel='noopener';a.click();}return;}
    if(action==='download-pdf'){if(currentPdf)downloadPdf(currentPdf.blob,pdfFilename(currentPdf.title));return;}
    if(action==='close'){await closeModal();return;}
    if(action==='forgot-password'){forgotPasswordScreen(root.querySelector('[name="email"]')?.value||'');return;}
    if(action==='auth-login'){await repo.cancelPasswordSetup();user=null;data=null;clearPdf();history.replaceState(null,'',new URL('./',location.href).pathname);loginScreen();return;}
    if(action==='retry'){await start();return;}
    if(action==='logout'){await repo.logout();user=null;data=null;clearPdf();await drafts.clear().catch(()=>{});await closeModal();loginScreen();return;}
    if(action==='obras'){data=null;clearPdf();await loadObras();obraScreen();return;}
    if(action==='select-obra'){await chooseObra(id);return;}
    if(action==='new-obra'){obraForm();return;}
    if(action==='edit-obra'){if(!owner())return;obraForm(data.obra);return;}
    if(action==='page'){page=el.dataset.page;aptId='';render();window.scrollTo({top:0});return;}
    if(action==='reload'){await refresh();notify('Dados sincronizados.');return;}
    if(action==='new-apt'){if(!owner())return;aptForm();return;}
    if(action==='edit-apt'){if(!owner())return;aptForm(rowById('apartamentos',id));return;}
    if(action==='open-apt'){aptId=id;quick='';render();window.scrollTo({top:0});return;}
    if(action==='back'){aptId='';render();return;}
    if(action==='quick-filter'){quick=el.dataset.value;render();return;}
    if(action==='conforme'||action==='finalizado'){await setApartmentStatus(action);return;}
    if(action==='new-item'){await openDraft();return;}
    if(action==='edit-item'){await openDraft(rowById('itens',id));return;}
    if(action==='reload-item'){if(!confirm('Descartar o rascunho local e abrir a versão salva mais recente?'))return;const latest=await repo.get('itens',id);if(!latest)throw new Error('Registro removido ou sem acesso. O rascunho local foi mantido.');clearTimeout(draftTimer);await drafts.remove(draftKey);draft=null;freePreviews();await openDraft(latest,true);return;}
    if(action==='resend-invite'){const invite=rowById('convites_obra',id);if(!owner()||!invite)return;try{const result=await repo.authorizeMember(data.obra.id,invite.email,invite.nome);notify(result.message);}finally{await refresh();}return;}
    if(action==='revoke-member'||action==='revoke-invite'){if(!owner()||!confirm('Remover o acesso desta pessoa à obra? Os registros feitos por ela serão mantidos.'))return;await repo.revokeMember(data.obra.id,action==='revoke-member'?{memberId:id}:{inviteId:id});await refresh();notify('Acesso removido. O histórico foi mantido.');return;}
    if(action==='go-settings'){await closeModal();page='ajustes';render();return;}
    if(action==='edit-catalog'){const row=rowById(el.dataset.table,id);showModal('Editar cadastro',`<form data-form="catalog" data-table="${el.dataset.table}" data-id="${id}">${flashError}${field('Nome','nome',row.nome,'required maxlength="100"')}<p class="small">Registros antigos mantêm o nome registrado na vistoria.</p><button type="submit" class="button primary wide">Salvar</button></form>`);return;}
    if(action==='delete-catalog'){const table=el.dataset.table,row=rowById(table,id),name=table==='ambientes'?'ambiente':'servico';if(table!=='prioridades'&&data.itens.some(i=>i[name]===row.nome))throw new Error('Este cadastro está em uso por registros. Preserve-o para manter os filtros e o histórico.');if(table==='prioridades'&&data.itens.some(i=>i.prioridade===row.nome))throw new Error('Esta prioridade está em uso por registros. Preserve-a para manter o histórico.');if(!confirm(`Excluir “${row.nome}”?`))return;await repo.remove(table,id);data[table]=data[table].filter(x=>x.id!==id);render();notify('Cadastro excluído.');return;}
    if(action==='inativar-catalog'||action==='reativar-catalog'){const table=el.dataset.table,row=rowById(table,id),updated=await repo.update(table,id,{ativo:action==='reativar-catalog'});data[table]=data[table].map(x=>x.id===id?updated:x);render();notify(updated.ativo?'Cadastro reativado.':'Cadastro inativado. O histórico é mantido.');return;}
    if(action==='delete-item'){if(!confirm('Excluir este registro fotográfico?'))return;await repo.remove('itens',id);await drafts.remove(draftKey);draft=null;await closeModal();await refresh();notify('Registro excluído.');return;}
    if(action==='save-pdf'){if(!currentPdf?.model||currentPdf.saved)return;const saved=await repo.saveReport(currentPdf);currentPdf.saved=true;data.relatorios=[saved,...data.relatorios.filter(r=>r.id!==saved.id)];render();notify('PDF salvo no app.');return;}
    if(action==='open-report'){const r=rowById('relatorios',id);const blob=await repo.download(REPORTS,r.pdf_path);pdfReady(blob,r.titulo,null,r.id,true);render();root.querySelector('.pdf-panel')?.scrollIntoView({behavior:'smooth',block:'center'});return;}
    if(action==='delete-report'){const r=rowById('relatorios',id);if(!confirm(`Excluir o relatório “${r.titulo}”?`))return;await repo.deleteReport(r);data.relatorios=data.relatorios.filter(x=>x.id!==id);if(currentPdf?.id===id)clearPdf();render();notify('Relatório excluído.');}
  }
  async function onClick(e){const el=e.target.closest('[data-action]');if(!el||el.disabled)return;const scope=dialog.open?dialog:root;try{el.disabled=true;await act(el);}catch(err){setError(scope,errorText(err));}finally{el.disabled=false;}}
  root.addEventListener('click',onClick);dialog.addEventListener('click',onClick);
  async function onSubmit(e){const form=e.target.closest('form[data-form]');if(!form)return;e.preventDefault();const values=Object.fromEntries(new FormData(form));await run(form,async()=>{
    const type=form.dataset.form;
    if(type==='recover'){await repo.resetPassword(values.email);form.querySelector('[data-recovery-message]').textContent='Se houver uma conta para este e-mail, você receberá o link para definir uma nova senha.';}
    if(type==='password'){try{user=await repo.setPassword(values.password,values.confirmation);}finally{form.querySelectorAll('input[type="password"]').forEach(input=>input.value='');}history.replaceState(null,'',new URL('./',location.href).pathname);await start();}
    if(type==='login'){user=await repo.login(values.email.trim(),values.password);await loadObras();obraScreen();}
    if(type==='member'){try{const result=await repo.authorizeMember(data.obra.id,values.email,values.nome);await refresh();notify(result.message);}catch(e){await refresh().catch(()=>{});notify(errorText(e),true);}}
    if(type==='obra'){const row={nome:values.nome.trim(),empresa:values.empresa.trim()};if(!row.nome)throw new Error('Informe o nome da obra.');const saved=form.dataset.id?await repo.update('obras',form.dataset.id,row):await repo.insert('obras',row);await loadObras();await closeModal();await chooseObra(saved.id);notify('Obra salva.');}
    if(type==='apt'){const pavimento=values.pavimento.trim();if(!pavimento)throw new Error('Informe o pavimento.');const nums=[...new Set(values.apartamento.split(',').map(s=>s.trim()).filter(Boolean))];if(!nums.length)throw new Error('Informe ao menos um apartamento.');if(form.dataset.id){if(nums.length!==1)throw new Error('Edite um apartamento por vez.');await repo.update('apartamentos',form.dataset.id,{pavimento,apartamento:nums[0]});}else {for(const apartamento of nums){if(data.apartamentos.some(a=>a.pavimento===pavimento&&a.apartamento===apartamento))continue;const saved=await repo.insert('apartamentos',{obra_id:data.obra.id,pavimento,apartamento,status:'nao_iniciado'});data.apartamentos.push(saved);}}await closeModal();await refresh();notify('Apartamentos salvos.');}
    if(type==='catalog'){const table=form.dataset.table,nome=values.nome.trim();if(!nome)throw new Error('Informe o nome.');if(data[table].some(r=>r.id!==form.dataset.id&&r.nome.toLocaleLowerCase('pt-BR')===nome.toLocaleLowerCase('pt-BR')))throw new Error('Esse nome já está cadastrado.');if(form.dataset.id){const old=rowById(table,form.dataset.id);const attr={ambientes:'ambiente',servicos:'servico',prioridades:'prioridade'}[table];if(old.nome!==nome&&data.itens.some(i=>i[attr]===old.nome))throw new Error('Este nome já está no histórico. Cadastre um novo nome para novos registros.');await repo.update(table,form.dataset.id,{nome});}else await repo.insert(table,{obra_id:data.obra.id,nome,ordem:data[table].length,ativo:true});await closeModal();await refresh();notify('Cadastro salvo.');}
    if(type==='item'){
      if(processing)throw new Error('Aguarde o processamento da foto.');
      Object.assign(draft,{ambiente:values.ambiente,servico:values.servico,status:values.status,observacao:values.observacao,responsavel:values.responsavel,prioridade:values.prioridade,prazo:values.prazo||''});
      busyDraft(true);clearTimeout(draftTimer);await rememberDraft();
      try {const saved=await repo.saveDraft(draft,msg=>{form.querySelector('[data-progress]').textContent=msg;});data.itens=[...data.itens.filter(i=>i.id!==saved.id),saved];await drafts.remove(draftKey).catch(()=>{});draft=null;busyDraft(false);await closeModal();render();notify('Registro e fotos salvos.');try{await refresh();}catch{notify('Registro salvo. Não foi possível sincronizar a lista; toque em Sincronizar.',true);}}
      catch(e){await rememberDraft();throw e;}finally{busyDraft(false);}
    }
    if(type==='report'){
      reportFilters={...values};
      const fresh=await repo.load(data.obra);data=fresh;const model=buildReportModel(data,values);
      const blob=await generatePdf(model,async(i,kind)=>{const path=i[`foto_${kind}_path`];if(path)return repo.download(PHOTOS,path);const legacy=i[`foto_${kind}_data`];if(/^data:image\/(jpeg|png);base64,/.test(legacy||''))return (await fetch(legacy)).blob();throw new Error('Foto indisponível.');},msg=>form.querySelector('[data-progress]').textContent=msg);
      pdfReady(blob,model.titulo,model);render();notify('PDF gerado com as imagens.');
    }
  });}
  root.addEventListener('submit',onSubmit);dialog.addEventListener('submit',onSubmit);
  root.addEventListener('input',e=>{const kind=e.target.dataset.filter;if(kind==='floor'||kind==='query'){floor=root.querySelector('[name="floor"]').value;query=root.querySelector('[name="query"]').value;root.querySelector('#apartment-list').innerHTML=apartmentList();}if(kind?.startsWith('pending')){floor=root.querySelector('[name="floor"]').value;pendingService=root.querySelector('[name="service"]').value;root.querySelector('#pending-list').innerHTML=pendingList();void resolvePhotos(root);}});
  root.addEventListener('input',e=>{const form=e.target.closest('form');if(form)form.dataset.dirty='true';});
  root.addEventListener('change',e=>{if(e.target.name==='tipo'){const form=e.target.closest('form');form.querySelector('.report-extra').hidden=!['servico','pendencias'].includes(e.target.value);}});
  dialog.addEventListener('input',e=>{if(!draft||e.target.type==='file'||!e.target.name)return;draft[e.target.name]=e.target.value;clearTimeout(draftTimer);draftTimer=setTimeout(()=>void rememberDraft(),400);});
  dialog.addEventListener('change',async e=>{
    const input=e.target,kind=input.dataset.photoInput;if(!kind||!input.files?.[0])return;
    const selected=input.files[0];const key=draftKey;
    // The file input itself receives the tap; it is never detached on selection.
    processing++;dialog.querySelectorAll('input[type="file"]').forEach(el=>el.disabled=true);dialog.querySelector('button[type="submit"]').disabled=true;
    const pe=dialog.querySelector('[data-photo-error]');pe.hidden=true;
    try {showPhotoPreview(kind,selected);const blob=await compressPhoto(selected);if(draftKey!==key||!draft)return;draft.photos[kind]={blob};showPhotoPreview(kind,blob);await rememberDraft();}
    catch(err){pe.textContent=errorText(err);pe.hidden=false;const previous=draft.photos[kind]?.blob;if(previous)showPhotoPreview(kind,previous);else dialog.querySelector(`[data-preview="${kind}"]`).innerHTML=photoHtml(draft,kind);}
    finally{input.value='';processing--;dialog.querySelectorAll('input[type="file"]').forEach(el=>el.disabled=!!processing);dialog.querySelector('button[type="submit"]').disabled=!!processing;}
  });
  window.addEventListener('online',()=>{notify('Conexão restabelecida. Você pode tentar salvar novamente.');});
  window.addEventListener('offline',()=>notify('Sem conexão. O rascunho permanece neste aparelho.',true));
  document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden'&&draft)void rememberDraft();else backgroundSync();});
  window.addEventListener('focus',backgroundSync);
  const syncTimer=setInterval(backgroundSync,20000);
  await start();
  return {reload:start,stop:()=>clearInterval(syncTimer)};
}
